spring.application.name=JavaNaumen
management.endpoints.web.exposure.include=*
spring.jmx.enabled=true
app.name=MoviesApp
app.version=1.0
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update